[theme]
primaryColor = "#f4a261"             # Soft orange
backgroundColor = "#ffffff"          # White
secondaryBackgroundColor = "#ffe8d6" # Light pastel orange (ดีมากสำหรับ card/background)
textColor = "#1f1f1f"                # Almost black (ลด contrast หน่อย)
font = "sans serif"
