[theme]
primaryColor = "#fb8500"          # Orange (matches Joinzy branding)
backgroundColor = "#FFFFFF"       # White background
secondaryBackgroundColor = "#FFE6CC"  # Light orange for card contrast
textColor = "#000000"             # Black text
font = "sans serif"               # Clean modern font
